### ISSUE TITLE
Add kafka source / sink

### ISSUE THREAD

**Issue by mtps** [provenance-io/event-stream#3]
## Summary

Add plugin sink / source to interface with kafka.

## Problem Definition

Why: Being able to direct the data into kafka and to read the data from kafka.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Conforms to interfaces defined in api

**Comment by wbaker-figure** [comment]
closed by #7
