### ISSUE TITLE
Add dependabot support

### ISSUE THREAD

**Issue by mtps** [provenance-io/event-stream#34]
## Summary of Bug

Utilize [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) to keep up to date with maven central and github action versioning.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by wbaker-figure** [comment]
closed by #46
