### ISSUE TITLE
Maven Publishing on Release Creation

### ISSUE THREAD

**Issue by mtps** [provenance-io/event-stream#9]
## Summary

Similar to how [hdwallet](https://github.com/provenance-io/hdwallet) is publishing out to maven central, get the event stream library publishing out to the same OSS repository (one artifact per lib-* entry).

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jphorec** [comment]
Implemented in https://github.com/provenance-io/event-stream/pull/20
